import Link from 'next/link';
import {ArrowRight,BarChart3,BookOpenCheck,BriefcaseBusiness,Factory,Globe2,GraduationCap,HeartHandshake,Landmark,Leaf,Scale,ShieldCheck,Store,Truck,Users} from 'lucide-react';

const operatingModel=[
  [BriefcaseBusiness,'Brand strategy','Concept positioning, commercial planning and disciplined portfolio management.'],
  [Factory,'Supply & quality','Procurement standards, vendor governance and consistent food-quality controls.'],
  [Store,'Development','Format planning, site evaluation and structured restaurant opening support.'],
  [GraduationCap,'People & learning','Role-based training, leadership development and operating playbooks.'],
  [BarChart3,'Performance','Shared reporting, operational reviews and continuous improvement programmes.'],
  [Truck,'Omnichannel growth','Dine-in, takeaway, delivery, catering and digital-ordering enablement.'],
];

export function CorporatePlatform(){return <>
  <section className="border-y border-[#E3E3E4] bg-white py-6" aria-label="Corporate audiences"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-5 px-6 lg:px-8"><p className="text-xs font-extrabold uppercase tracking-[.22em] text-[#717275]">Working with Brandz</p><div className="flex flex-wrap gap-x-8 gap-y-3 text-sm font-bold">{['Franchise partners','Property owners','Suppliers','Corporate clients','Future talent'].map(item=><Link href="/contact" key={item} className="group flex items-center gap-2 hover:text-[#F05535]">{item}<ArrowRight size={14} className="transition group-hover:translate-x-1"/></Link>)}</div></div></section>

  <section className="bg-[#F7F7F7] py-24" id="capabilities"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div className="lg:sticky lg:top-28 lg:self-start"><p className="eyebrow">Our operating platform</p><h2 className="section-title">Shared strength.<br/>Brand-level focus.</h2><p className="mt-6 max-w-md text-lg leading-8 text-[#717275]">Brandz combines specialist group functions with the entrepreneurial energy of every concept. The result is a platform designed for consistency, accountability and sustainable scale.</p><Link href="/contact" className="mt-8 inline-flex items-center gap-2 font-bold text-[#F05535]">Discuss a partnership <ArrowRight size={17}/></Link></div><div className="grid gap-4 sm:grid-cols-2">{operatingModel.map(([Icon,title,copy],i)=><article className="rounded-xl bg-white p-7 shadow-sm" key={title as string}><div className="flex items-center justify-between"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[#FFF0EC] text-[#F05535]">{typeof Icon!=='string'&&<Icon size={22}/>}</div><span className="font-heading text-sm font-bold text-[#B8B8BA]">0{i+1}</span></div><h3 className="mt-8 font-heading text-xl font-bold">{title as string}</h3><p className="mt-3 text-sm leading-6 text-[#717275]">{copy as string}</p></article>)}</div></div></div></section>

  <section className="overflow-hidden bg-[#292A2D] py-24 text-white" id="governance"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="grid gap-14 lg:grid-cols-2 lg:items-center"><div className="relative"><img src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=85" alt="Corporate leadership meeting" className="h-[560px] w-full rounded-xl object-cover opacity-80" loading="lazy"/><div className="absolute bottom-6 left-6 right-6 rounded-2xl border border-white/10 bg-[#292A2D]/90 p-5 backdrop-blur"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#F05535]">A portfolio built on trust</p><p className="mt-2 text-sm leading-6 text-white/60">Clear standards, accountable leadership and long-term partner relationships guide how we grow.</p></div></div><div><p className="eyebrow text-[#F05535]">Governance & stewardship</p><h2 className="section-title text-white">Responsible decisions are part of the operating model.</h2><p className="mt-6 text-lg leading-8 text-white/60">Our governance framework connects group direction with brand execution. Policies, review forums and defined responsibilities help protect guests, partners, teams and brand equity.</p><div className="mt-10 space-y-3">{[[Scale,'Ethical business','Clear expectations for conduct, conflicts and fair dealing.'],[ShieldCheck,'Risk & compliance','Structured oversight of food safety, operations and regulatory responsibilities.'],[BookOpenCheck,'Performance review','Consistent reporting and action-focused operating reviews.'],[Users,'People accountability','Defined ownership, training and leadership succession.']].map(([Icon,title,copy]:any)=><div key={title} className="flex gap-4 rounded-2xl border border-white/10 p-5"><Icon className="mt-1 shrink-0 text-[#F05535]" size={21}/><div><h3 className="font-bold">{title}</h3><p className="mt-1 text-sm leading-6 text-white/50">{copy}</p></div></div>)}</div></div></div></div></section>

  <section className="py-24" id="responsibility"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="flex flex-col justify-between gap-7 md:flex-row md:items-end"><div><p className="eyebrow">Responsible hospitality</p><h2 className="section-title max-w-3xl">Growth that creates value beyond the restaurant.</h2></div><p className="max-w-md leading-7 text-[#717275]">We focus our responsibility agenda on the areas closest to our operations and communities.</p></div><div className="mt-14 grid gap-5 lg:grid-cols-3">{[[Leaf,'Better operations','Working toward smarter resource use, waste awareness and responsible sourcing across the portfolio.','Environment'],[HeartHandshake,'Stronger communities','Supporting local enterprise, inclusive opportunity and neighbourhood participation.','Community'],[Users,'Meaningful careers','Building practical skills, fair workplaces and pathways for people to grow with the group.','People']].map(([Icon,title,copy,label]:any)=><article className="group relative min-h-[330px] overflow-hidden rounded-xl bg-[#F7F7F7] p-8" key={title}><div className="absolute -bottom-16 -right-16 h-48 w-48 rounded-md bg-[#F05535]/10 transition duration-500 group-hover:scale-125"/><Icon size={28} className="relative text-[#F05535]"/><p className="relative mt-14 text-xs font-extrabold uppercase tracking-[.2em] text-[#F05535]">{label}</p><h3 className="relative mt-3 font-heading text-2xl font-bold">{title}</h3><p className="relative mt-4 max-w-sm text-sm leading-7 text-[#717275]">{copy}</p></article>)}</div></div></section>

  <section className="bg-[#343538] py-24 text-white"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow text-[#F05535]">Corporate access</p><h2 className="section-title text-white">The right conversation starts here.</h2><p className="mt-5 leading-7 text-white/55">Connect with the relevant Brandz team for partnerships, property, supply, careers or corporate enquiries.</p></div><div className="grid gap-px overflow-hidden rounded-xl border border-white/10 bg-white/10 sm:grid-cols-2">{[[Landmark,'Franchise & investment','Explore brand formats and partnership pathways.'],[Globe2,'Property & expansion','Share high-potential locations and development opportunities.'],[Truck,'Supplier partnerships','Introduce products and services aligned with our standards.'],[Users,'Careers at Brandz','Build experience across a diverse hospitality portfolio.']].map(([Icon,title,copy]:any)=><Link href="/contact" key={title} className="group bg-[#343538] p-7 transition hover:bg-white/[.04]"><Icon className="text-[#F05535]"/><div className="mt-8 flex items-center justify-between gap-4"><h3 className="font-bold">{title}</h3><ArrowRight size={17} className="transition group-hover:translate-x-1"/></div><p className="mt-3 text-sm leading-6 text-white/50">{copy}</p></Link>)}</div></div></div></section>
  </>}
