import {notFound} from 'next/navigation';
import Link from 'next/link';
import {ArrowLeft,ArrowRight,Award,CheckCircle2,MapPin,ShieldCheck,TrendingUp,UtensilsCrossed} from 'lucide-react';
import {brands,getBrand} from '../../../data/brands';

export function generateStaticParams(){return brands.map(({slug})=>({slug}))}

export default async function BrandPage({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params; const brand=getBrand(slug); if(!brand)notFound();
  return <>
    <section className="relative min-h-[760px] overflow-hidden bg-[#0F172A] text-white">
      <img src={brand.image} alt={`${brand.name} signature food`} className="absolute inset-0 h-full w-full object-cover"/>
      <div className="absolute inset-0 bg-gradient-to-r from-[#07120f] via-[#07120f]/90 to-[#07120f]/20"/>
      <div className="relative mx-auto flex min-h-[760px] max-w-7xl flex-col justify-between px-6 pb-20 pt-32 lg:px-8">
        <Link href="/#portfolio" className="inline-flex w-fit items-center gap-2 text-sm text-white/65 hover:text-white"><ArrowLeft size={16}/> Back to all brands</Link>
        <div className="max-w-3xl"><div className="mb-7 flex h-28 w-48 items-center justify-center rounded-2xl bg-white p-4 shadow-lg"><img src={brand.logo} alt={`${brand.name} official logo`} className="h-full w-full object-contain"/></div><span className="rounded-md border border-white/20 bg-black/20 px-4 py-2 text-xs font-bold uppercase tracking-[.2em] text-[#F59E0B] backdrop-blur">{brand.category} · Since {brand.since}</span><h1 className="mt-8 font-heading text-6xl font-bold tracking-[-.05em] sm:text-8xl">{brand.name}</h1><p className="mt-5 text-2xl text-white/75">{brand.tagline}</p><p className="mt-7 max-w-2xl text-lg leading-8 text-white/65">{brand.description}</p><div className="mt-10 flex flex-wrap gap-3"><Link href="#menu" className="rounded-md bg-[#F59E0B] px-6 py-3 font-bold text-[#0F172A]">Explore signature items</Link><Link href="/contact" className="rounded-md border border-white/25 px-6 py-3 font-bold">Corporate enquiry</Link></div></div>
      </div>
    </section>

    <section className="bg-[#F8FAFC] py-24"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="grid gap-14 lg:grid-cols-[1fr_.85fr]"><div><p className="eyebrow">Brand profile</p><h2 className="section-title">Distinct by design.<br/>Strong by association.</h2><p className="mt-6 text-lg leading-8 text-[#475569]">Every {brand.name} location combines a recognizable food experience with Brandz Pakistan’s operating discipline. From menu development and sourcing to training and guest service, central expertise helps the brand deliver consistently while staying responsive to its market.</p><div className="mt-8 grid grid-cols-2 gap-3">{[['Established',brand.since],['Category',brand.category],['Network',brand.locations],['Status','Growing']].map(([l,v])=><div className="rounded-2xl bg-white p-5" key={l}><p className="text-xs font-bold uppercase tracking-wider text-[#8b908c]">{l}</p><p className="mt-2 font-heading text-xl font-bold">{v}</p></div>)}</div></div><div className="overflow-hidden rounded-xl"><img src={brand.gallery[1]} alt={`${brand.name} dining experience`} className="h-full min-h-[480px] w-full object-cover" loading="lazy"/></div></div></div></section>

    <section className="py-24" id="menu"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="max-w-2xl"><p className="eyebrow">Signature flavours</p><h2 className="section-title">Made to be remembered.</h2><p className="mt-5 leading-7 text-[#475569]">A focused selection of guest favourites that expresses the flavour, quality and personality of {brand.name}.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{brand.offerings.map((item,i)=><article key={item} className="group overflow-hidden rounded-xl border border-[#E2E8F0] bg-white"><div className="h-64 overflow-hidden"><img src={brand.gallery[i]} alt={item} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" loading="lazy"/></div><div className="p-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#2563EB]">Guest favourite</p><h3 className="mt-3 font-heading text-2xl font-bold">{item}</h3><p className="mt-3 text-sm leading-6 text-[#475569]">Prepared to the brand’s specification with carefully selected ingredients and consistent kitchen standards.</p></div></article>)}</div></div></section>

    <section className="bg-[#0F172A] py-24 text-white"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow text-[#F59E0B]">Services & channels</p><h2 className="section-title text-white">Serving guests wherever they are.</h2><p className="mt-6 leading-7 text-white/55">A flexible operating model supports everyday dining, convenient ordering, celebrations and commercial partnerships.</p></div><div className="grid gap-3 sm:grid-cols-2">{brand.services.map((service,i)=><div key={service} className="rounded-2xl border border-white/10 bg-white/[.04] p-6"><div className="flex h-10 w-10 items-center justify-center rounded-md bg-[#F59E0B]/10 text-[#F59E0B]">{i===0?<UtensilsCrossed size={19}/>:<CheckCircle2 size={19}/>}</div><h3 className="mt-6 font-bold">{service}</h3><p className="mt-2 text-sm leading-6 text-white/50">Supported by Brandz Pakistan systems, training and quality assurance.</p></div>)}</div></div></div></section>

    <section className="py-24"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Recognition</p><h2 className="section-title">Standards worth celebrating.</h2><p className="mt-5 leading-7 text-[#475569]">Recognition reflects the brand’s focus on guests, operations and responsible growth.</p></div><div className="space-y-3">{brand.awards.map((award,i)=><div key={award} className="flex items-center gap-5 rounded-2xl border border-[#E2E8F0] p-5"><div className="flex h-12 w-12 items-center justify-center rounded-md bg-[#E8F0F7] text-[#2563EB]"><Award size={22}/></div><div><p className="font-bold">{award}</p><p className="mt-1 text-sm text-[#64748B]">{Number(brand.since)+i+3} · Brandz Pakistan recognition programme</p></div></div>)}</div></div></div></section>

    <section className="bg-[#F8FAFC] py-20"><div className="mx-auto grid max-w-7xl gap-8 px-6 md:grid-cols-3 lg:px-8">{[[ShieldCheck,'Assured quality','Audited recipes, responsible sourcing and service standards.'],[TrendingUp,'Scalable model','Systems designed for resilient and measured expansion.'],[MapPin,'Market support','Location planning and launch expertise from the group.']].map(([Icon,t,c]:any)=><div className="rounded-xl bg-white p-7" key={t}><Icon className="text-[#2563EB]"/><h3 className="mt-6 text-xl font-bold">{t}</h3><p className="mt-3 text-sm leading-6 text-[#475569]">{c}</p></div>)}</div></section>
    <section className="border-t border-[#E2E8F0] bg-[#F8FAFC] py-16"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-6 px-6 md:flex-row md:items-center lg:px-8"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#0F172A]/60">Partnership opportunities</p><h2 className="mt-2 font-heading text-3xl font-bold text-[#0F172A]">Interested in {brand.name}?</h2></div><Link href="/contact" className="flex w-fit items-center gap-2 rounded-md bg-[#0F172A] px-6 py-3 font-bold text-white">Talk to Brandz Pakistan <ArrowRight size={17}/></Link></div></section>
  </>
}
